name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017


    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v5

      - name: install dependencies
        run : npm install

      - name: run test
        run : npm test
        env:
          MONGODB_URI: mongodb://localhost:27017
      